{{ if .Values.deleteWorker.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "qryn-all-in-one.fullname" . }}-delete-worker
  labels:
    io.metrico.service: qryn-delete-worker
    {{- include "qryn-all-in-one.labels" . | nindent 4 }}
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  schedule: {{.Values.deleteWorker.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        io.metrico.service: qryn-delete-worker
        {{- include "qryn-all-in-one.selectorLabels" . | nindent 8 }}
      {{- with .Values.deleteWorker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      template:
        spec:
          containers:
            - envFrom:
                - configMapRef:
                    name: {{ include "qryn-all-in-one.fullname" . }}-qryn
              image: {{ .Values.deleteWorker.image.repository }}:{{ .Values.deleteWorker.image.tag | default .Chart.AppVersion }}
              imagePullPolicy: {{ .Values.deleteWorker.imagePullPolicy }}
              name: qryn-delete-worker
              resources: {{ toYaml .Values.deleteWorker.resources | nindent 16 }}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          imagePullSecrets:
            - name: qryn-dckr
          restartPolicy: Never
          securityContext: {}
          terminationGracePeriodSeconds: 30
          {{- with .Values.deleteWorker.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.deleteWorker.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.deleteWorker.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
{{ end }}